-- Sistema WMS: «Ficha producto Dropi». Réplica de los productos de Dropi: la lista y, al pulsar un producto, su ficha lateral con las
-- secciones de «Crear Producto» (General, Stock / Variables y stock, Imagen, Videos, Recursos adicionales, Productos privados y
-- Garantías), más archivar, aprobado e historial de existencia.

-- Bodegas del proveedor por país (en Dropi cada producto lleva su stock por bodega). Se siembra la que aparece hoy en Dropi Panamá.
create table if not exists wms_bodegas (
  id uuid primary key default gen_random_uuid(),
  pais_id uuid not null references paises(id),
  nombre text not null,
  activa boolean not null default true,
  creado_en timestamptz not null default now(),
  unique (pais_id, nombre)
);

create table if not exists wms_dropi_productos (
  id uuid primary key default gen_random_uuid(),
  -- Número corto que se ve en la lista (el «ID» de Dropi).
  numero bigint generated by default as identity,
  pais_id uuid not null references paises(id),
  nombre text not null,
  nombre_guia text,
  publicacion text not null default 'publico' check (publicacion in ('publico', 'privado')),
  aprobado boolean not null default false,
  archivado boolean not null default false,
  -- Peso en gramos y medidas en centímetros (como en Dropi).
  peso numeric(10, 3),
  longitud numeric(10, 2),
  ancho numeric(10, 2),
  alto numeric(10, 2),
  precio numeric(12, 2),
  precio_sugerido numeric(12, 2),
  tipo text not null default 'simple' check (tipo in ('simple', 'variable')),
  categorias text[] not null default '{}',
  sku text,
  descripcion text not null default '',
  descripcion_app text not null default '',
  -- Producto simple: { "<bodega_id>": cantidad }.
  stock jsonb not null default '{}',
  -- Producto variable: atributos [{nombre, valores[]}] y sus variaciones [{combinacion, sku, precio, precio_sugerido, stock{}}].
  atributos jsonb not null default '[]',
  variaciones jsonb not null default '[]',
  garantias jsonb not null default '{}',
  privados jsonb not null default '[]',
  recursos jsonb not null default '[]',
  creado_por uuid references auth.users(id),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists wms_dropi_producto_medios (
  id uuid primary key default gen_random_uuid(),
  producto_id uuid not null references wms_dropi_productos(id) on delete cascade,
  ruta text not null,
  nombre_archivo text,
  tipo text not null default 'imagen' check (tipo in ('imagen', 'video')),
  posicion integer not null default 0
);

create index if not exists wms_dropi_productos_pais_idx on wms_dropi_productos (pais_id, creado_en desc);
create index if not exists wms_dropi_medios_producto_idx on wms_dropi_producto_medios (producto_id, posicion);

alter table wms_bodegas enable row level security;
alter table wms_dropi_productos enable row level security;
alter table wms_dropi_producto_medios enable row level security;

drop policy if exists "authenticated read/write" on wms_bodegas;
create policy "authenticated read/write" on wms_bodegas for all using (auth.role() = 'authenticated');
drop policy if exists "authenticated read/write" on wms_dropi_productos;
create policy "authenticated read/write" on wms_dropi_productos for all using (auth.role() = 'authenticated');
drop policy if exists "authenticated read/write" on wms_dropi_producto_medios;
create policy "authenticated read/write" on wms_dropi_producto_medios for all using (auth.role() = 'authenticated');

insert into wms_bodegas (pais_id, nombre)
select id, 'Proveedor Ecomfive (Ave Centenario, Costa del Este)' from paises where codigo = 'PA'
on conflict do nothing;

-- Las imágenes y videos usan el mismo bucket público de la ficha Shopify (`wms-productos`), bajo `dropi/`.
insert into storage.buckets (id, name, public)
values ('wms-productos', 'wms-productos', true)
on conflict (id) do nothing;

insert into permisos_rol (rol_id, modulo)
select id, 'wms-productos-dropi' from roles where nombre = 'Admin'
on conflict do nothing;
