-- CRM de dropshippers, segunda versión: ficha completa, países donde vende cada uno, pedidos manuales y casos de soporte.
--
-- Un dropshipper puede vender en varios países con nosotros (p. ej. Panamá y Costa Rica) y es de cualquier parte de
-- Latinoamérica. Por eso:
--   * `dropshipper_paises` dice en qué países vende. `dropshippers.pais_id` queda como el país principal (el primero).
--   * `dropshippers.pais_origen` es el país de donde es (código ISO de 2 letras, p. ej. 'CO'); no es una clave de `paises`.
--   * los pedidos y los casos llevan su país: las ventas de Costa Rica (colones) y de Panamá (dólares) no se suman.
--
-- Hasta que Dropi alimente los pedidos, se cargan a mano (origen = 'manual'); el mismo campo permite que una integración
-- los escriba después sin cambiar la tabla.
-- NO se corre mientras el módulo esté en MODO_DEMO (ver src/app/(app)/crm-dropshippers/datos-demo.ts).

-- Código DS-0001, DS-0002… automático (la secuencia evita choques si dos personas crean a la vez).
create sequence if not exists dropshippers_codigo_seq;

alter table dropshippers
  add column if not exists codigo text unique,
  add column if not exists tienda text,
  add column if not exists ciudad text,
  add column if not exists pais_origen text check (pais_origen is null or pais_origen ~ '^[A-Z]{2}$'),
  add column if not exists nivel text not null default 'nuevo' check (nivel in ('nuevo', 'regular', 'vip')),
  add column if not exists fecha_ingreso date,
  add column if not exists responsable_id uuid references perfiles(id) on delete set null,
  add column if not exists etiquetas text[] not null default '{}',
  -- Enlace con la conversación de WhatsApp en Chatwoot (fase de chat).
  add column if not exists chatwoot_contact_id bigint;

alter table dropshippers
  alter column codigo set default ('DS-' || lpad(nextval('dropshippers_codigo_seq')::text, 4, '0'));
update dropshippers set codigo = 'DS-' || lpad(nextval('dropshippers_codigo_seq')::text, 4, '0') where codigo is null;

-- El WhatsApp identifica a la persona (con él se enlaza el chat): no puede repetirse entre dos dropshippers.
create unique index if not exists dropshippers_telefono_unico on dropshippers (contacto_telefono) where contacto_telefono is not null;

-- Países donde vende cada dropshipper.
create table if not exists dropshipper_paises (
  dropshipper_id uuid not null references dropshippers(id) on delete cascade,
  pais_id uuid not null references paises(id),
  creado_en timestamptz not null default now(),
  primary key (dropshipper_id, pais_id)
);
-- Los que ya existían venden en su país actual.
insert into dropshipper_paises (dropshipper_id, pais_id) select id, pais_id from dropshippers on conflict do nothing;

create table if not exists pedidos_dropshipper (
  id uuid primary key default gen_random_uuid(),
  dropshipper_id uuid not null,
  pais_id uuid not null,
  numero text,
  fecha date not null,
  monto numeric(12, 2) not null check (monto >= 0),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'entregado', 'devuelto', 'cancelado')),
  origen text not null default 'manual' check (origen in ('manual', 'dropi')),
  creado_en timestamptz not null default now(),
  -- Solo se registra un pedido en un país donde ese dropshipper vende.
  foreign key (dropshipper_id, pais_id) references dropshipper_paises (dropshipper_id, pais_id) on delete cascade
);

create table if not exists casos_dropshipper (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity,
  dropshipper_id uuid not null,
  pais_id uuid not null,
  titulo text not null,
  tipo text not null check (tipo in ('problema', 'pedido', 'pago', 'devolucion', 'otro')),
  prioridad text not null default 'normal' check (prioridad in ('baja', 'normal', 'alta')),
  estado text not null default 'abierto' check (estado in ('abierto', 'en_curso', 'resuelto')),
  numero_pedido text,
  canal text not null default 'whatsapp' check (canal in ('whatsapp', 'correo', 'llamada', 'otro')),
  responsable_id uuid references perfiles(id) on delete set null,
  abierto_en timestamptz not null default now(),
  primera_respuesta_en timestamptz,
  resuelto_en timestamptz,
  foreign key (dropshipper_id, pais_id) references dropshipper_paises (dropshipper_id, pais_id) on delete cascade
);

create index if not exists pedidos_dropshipper_ds_pais_fecha on pedidos_dropshipper (dropshipper_id, pais_id, fecha desc);
create index if not exists casos_dropshipper_pais_estado on casos_dropshipper (pais_id, estado);

alter table dropshipper_paises enable row level security;
alter table pedidos_dropshipper enable row level security;
alter table casos_dropshipper enable row level security;

-- Sin políticas, a propósito: la app solo toca estas tablas desde el servidor con la clave de servicio, que se salta RLS.
-- (Una política «authenticated read/write» daría acceso total a cualquier cuenta con sesión; ver migración 0063 y
-- SEGURIDAD.md.)

-- Una fila por dropshipper y país con lo que se suma en la base (no en JavaScript): pedidos y ventas del mes en curso,
-- último pedido y casos abiertos. Es lo que leen el directorio, el ranking y las tarjetas de cada país.
create or replace view crm_dropshippers_resumen
with (security_invoker = true) as
select
  dp.dropshipper_id as id,
  dp.pais_id,
  coalesce(p.pedidos_mes, 0) as pedidos_mes,
  coalesce(p.ventas_mes, 0) as ventas_mes,
  p.ultimo_pedido,
  coalesce(c.casos_abiertos, 0) as casos_abiertos
from dropshipper_paises dp
left join (
  select
    dropshipper_id,
    pais_id,
    count(*) filter (where fecha >= date_trunc('month', current_date) and estado <> 'cancelado') as pedidos_mes,
    coalesce(sum(monto) filter (where fecha >= date_trunc('month', current_date) and estado not in ('cancelado', 'devuelto')), 0) as ventas_mes,
    max(fecha) filter (where estado <> 'cancelado') as ultimo_pedido
  from pedidos_dropshipper
  group by dropshipper_id, pais_id
) p on p.dropshipper_id = dp.dropshipper_id and p.pais_id = dp.pais_id
left join (
  select dropshipper_id, pais_id, count(*) as casos_abiertos
  from casos_dropshipper
  where estado <> 'resuelto'
  group by dropshipper_id, pais_id
) c on c.dropshipper_id = dp.dropshipper_id and c.pais_id = dp.pais_id;
