-- CRM de dropshippers, segunda versión: ficha completa, pedidos manuales y casos de soporte.
-- Hasta que Dropi alimente los pedidos, se cargan a mano (origen = 'manual'); el mismo campo permite
-- que una integración los escriba después sin cambiar la tabla.
-- NO se corre mientras el módulo esté en MODO_DEMO (ver src/app/(app)/crm-dropshippers/datos-demo.ts).

alter table dropshippers
  add column if not exists codigo text unique,
  add column if not exists tienda text,
  add column if not exists ciudad text,
  add column if not exists nivel text not null default 'nuevo' check (nivel in ('nuevo', 'regular', 'vip')),
  add column if not exists fecha_ingreso date,
  add column if not exists responsable_id uuid references perfiles(id) on delete set null,
  add column if not exists etiquetas text[] not null default '{}',
  -- Enlace con la conversación de WhatsApp en Chatwoot (fase 2).
  add column if not exists chatwoot_contact_id bigint;

create table if not exists pedidos_dropshipper (
  id uuid primary key default gen_random_uuid(),
  dropshipper_id uuid not null references dropshippers(id) on delete cascade,
  numero text,
  fecha date not null,
  monto numeric(12, 2) not null check (monto >= 0),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'entregado', 'devuelto', 'cancelado')),
  origen text not null default 'manual' check (origen in ('manual', 'dropi')),
  creado_en timestamptz not null default now()
);

create table if not exists casos_dropshipper (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity,
  dropshipper_id uuid not null references dropshippers(id) on delete cascade,
  titulo text not null,
  tipo text not null check (tipo in ('problema', 'pedido', 'pago', 'devolucion', 'otro')),
  prioridad text not null default 'normal' check (prioridad in ('baja', 'normal', 'alta')),
  estado text not null default 'abierto' check (estado in ('abierto', 'en_curso', 'resuelto')),
  numero_pedido text,
  canal text not null default 'whatsapp' check (canal in ('whatsapp', 'correo', 'llamada', 'otro')),
  responsable_id uuid references perfiles(id) on delete set null,
  abierto_en timestamptz not null default now(),
  primera_respuesta_en timestamptz,
  resuelto_en timestamptz
);

create index if not exists pedidos_dropshipper_ds_fecha on pedidos_dropshipper (dropshipper_id, fecha desc);
create index if not exists casos_dropshipper_ds_estado on casos_dropshipper (dropshipper_id, estado);

alter table pedidos_dropshipper enable row level security;
alter table casos_dropshipper enable row level security;

create policy "authenticated read/write" on pedidos_dropshipper for all using (auth.role() = 'authenticated');
create policy "authenticated read/write" on casos_dropshipper for all using (auth.role() = 'authenticated');

-- Una fila por dropshipper con lo que se suma en la base (no en JavaScript): pedidos y ventas del mes en curso,
-- último pedido y casos abiertos. Es lo que leen el directorio, el ranking y las tarjetas.
create or replace view crm_dropshippers_resumen
with (security_invoker = true) as
select
  d.id,
  coalesce(p.pedidos_mes, 0) as pedidos_mes,
  coalesce(p.ventas_mes, 0) as ventas_mes,
  p.ultimo_pedido,
  coalesce(c.casos_abiertos, 0) as casos_abiertos
from dropshippers d
left join (
  select
    dropshipper_id,
    count(*) filter (where fecha >= date_trunc('month', current_date) and estado <> 'cancelado') as pedidos_mes,
    coalesce(sum(monto) filter (where fecha >= date_trunc('month', current_date) and estado not in ('cancelado', 'devuelto')), 0) as ventas_mes,
    max(fecha) filter (where estado <> 'cancelado') as ultimo_pedido
  from pedidos_dropshipper
  group by dropshipper_id
) p on p.dropshipper_id = d.id
left join (
  select dropshipper_id, count(*) as casos_abiertos
  from casos_dropshipper
  where estado <> 'resuelto'
  group by dropshipper_id
) c on c.dropshipper_id = d.id;
